// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// NewAdminVerifyUserCodeRequestParams creates a new AdminVerifyUserCodeRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAdminVerifyUserCodeRequestParams() *AdminVerifyUserCodeRequestParams {
	return &AdminVerifyUserCodeRequestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAdminVerifyUserCodeRequestParamsWithTimeout creates a new AdminVerifyUserCodeRequestParams object
// with the ability to set a timeout on a request.
func NewAdminVerifyUserCodeRequestParamsWithTimeout(timeout time.Duration) *AdminVerifyUserCodeRequestParams {
	return &AdminVerifyUserCodeRequestParams{
		timeout: timeout,
	}
}

// NewAdminVerifyUserCodeRequestParamsWithContext creates a new AdminVerifyUserCodeRequestParams object
// with the ability to set a context for a request.
func NewAdminVerifyUserCodeRequestParamsWithContext(ctx context.Context) *AdminVerifyUserCodeRequestParams {
	return &AdminVerifyUserCodeRequestParams{
		Context: ctx,
	}
}

// NewAdminVerifyUserCodeRequestParamsWithHTTPClient creates a new AdminVerifyUserCodeRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewAdminVerifyUserCodeRequestParamsWithHTTPClient(client *http.Client) *AdminVerifyUserCodeRequestParams {
	return &AdminVerifyUserCodeRequestParams{
		HTTPClient: client,
	}
}

/* AdminVerifyUserCodeRequestParams contains all the parameters to send to the API endpoint
   for the admin verify user code request operation.

   Typically these are written to a http.Request.
*/
type AdminVerifyUserCodeRequestParams struct {

	// Body.
	Body *models.VerifyUserCodeRequest

	// DeviceChallenge.
	DeviceChallenge string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the admin verify user code request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AdminVerifyUserCodeRequestParams) WithDefaults() *AdminVerifyUserCodeRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the admin verify user code request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AdminVerifyUserCodeRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) WithTimeout(timeout time.Duration) *AdminVerifyUserCodeRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) WithContext(ctx context.Context) *AdminVerifyUserCodeRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) WithHTTPClient(client *http.Client) *AdminVerifyUserCodeRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) WithBody(body *models.VerifyUserCodeRequest) *AdminVerifyUserCodeRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) SetBody(body *models.VerifyUserCodeRequest) {
	o.Body = body
}

// WithDeviceChallenge adds the deviceChallenge to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) WithDeviceChallenge(deviceChallenge string) *AdminVerifyUserCodeRequestParams {
	o.SetDeviceChallenge(deviceChallenge)
	return o
}

// SetDeviceChallenge adds the deviceChallenge to the admin verify user code request params
func (o *AdminVerifyUserCodeRequestParams) SetDeviceChallenge(deviceChallenge string) {
	o.DeviceChallenge = deviceChallenge
}

// WriteToRequest writes these params to a swagger request
func (o *AdminVerifyUserCodeRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// query param device_challenge
	qrDeviceChallenge := o.DeviceChallenge
	qDeviceChallenge := qrDeviceChallenge
	if qDeviceChallenge != "" {

		if err := r.SetQueryParam("device_challenge", qDeviceChallenge); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
