// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// AdminVerifyUserCodeRequestReader is a Reader for the AdminVerifyUserCodeRequest structure.
type AdminVerifyUserCodeRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AdminVerifyUserCodeRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAdminVerifyUserCodeRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAdminVerifyUserCodeRequestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAdminVerifyUserCodeRequestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAdminVerifyUserCodeRequestOK creates a AdminVerifyUserCodeRequestOK with default headers values
func NewAdminVerifyUserCodeRequestOK() *AdminVerifyUserCodeRequestOK {
	return &AdminVerifyUserCodeRequestOK{}
}

/* AdminVerifyUserCodeRequestOK describes a response with status code 200, with default header values.

completedRequest
*/
type AdminVerifyUserCodeRequestOK struct {
	Payload *models.CompletedRequest
}

func (o *AdminVerifyUserCodeRequestOK) Error() string {
	return fmt.Sprintf("[PUT /oauth2/auth/requests/device/verify][%d] adminVerifyUserCodeRequestOK  %+v", 200, o.Payload)
}
func (o *AdminVerifyUserCodeRequestOK) GetPayload() *models.CompletedRequest {
	return o.Payload
}

func (o *AdminVerifyUserCodeRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CompletedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdminVerifyUserCodeRequestNotFound creates a AdminVerifyUserCodeRequestNotFound with default headers values
func NewAdminVerifyUserCodeRequestNotFound() *AdminVerifyUserCodeRequestNotFound {
	return &AdminVerifyUserCodeRequestNotFound{}
}

/* AdminVerifyUserCodeRequestNotFound describes a response with status code 404, with default header values.

jsonError
*/
type AdminVerifyUserCodeRequestNotFound struct {
	Payload *models.JSONError
}

func (o *AdminVerifyUserCodeRequestNotFound) Error() string {
	return fmt.Sprintf("[PUT /oauth2/auth/requests/device/verify][%d] adminVerifyUserCodeRequestNotFound  %+v", 404, o.Payload)
}
func (o *AdminVerifyUserCodeRequestNotFound) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AdminVerifyUserCodeRequestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdminVerifyUserCodeRequestInternalServerError creates a AdminVerifyUserCodeRequestInternalServerError with default headers values
func NewAdminVerifyUserCodeRequestInternalServerError() *AdminVerifyUserCodeRequestInternalServerError {
	return &AdminVerifyUserCodeRequestInternalServerError{}
}

/* AdminVerifyUserCodeRequestInternalServerError describes a response with status code 500, with default header values.

jsonError
*/
type AdminVerifyUserCodeRequestInternalServerError struct {
	Payload *models.JSONError
}

func (o *AdminVerifyUserCodeRequestInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /oauth2/auth/requests/device/verify][%d] adminVerifyUserCodeRequestInternalServerError  %+v", 500, o.Payload)
}
func (o *AdminVerifyUserCodeRequestInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *AdminVerifyUserCodeRequestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
