/*
 * Ory Hydra API
 *
 * Documentation for all of Ory Hydra's APIs.
 *
 * API version: 1.0.0
 * Contact: hi@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// OAuth2ApiDeviceAuthorizationResponse Ory's OAuth 2.0 Device Authorization API
type OAuth2ApiDeviceAuthorizationResponse struct {
	// The device verification code.
	DeviceCode *string `json:"device_code,omitempty"`
	// The lifetime in seconds of the \"device_code\" and \"user_code\".
	ExpiresIn *int64 `json:"expires_in,omitempty"`
	// The minimum amount of time in seconds that the client SHOULD wait between polling requests to the token endpoint.  If no value is provided, clients MUST use 5 as the default.
	Interval *int64 `json:"interval,omitempty"`
	// The end-user verification code.
	UserCode *string `json:"user_code,omitempty"`
	// The end-user verification URI on the authorization server.  The URI should be short and easy to remember as end users will be asked to manually type it into their user agent.
	VerificationUri *string `json:"verification_uri,omitempty"`
	// A verification URI that includes the \"user_code\" (or other information with the same function as the \"user_code\"), which is designed for non-textual transmission.
	VerificationUriComplete *string `json:"verification_uri_complete,omitempty"`
}

// NewOAuth2ApiDeviceAuthorizationResponse instantiates a new OAuth2ApiDeviceAuthorizationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuth2ApiDeviceAuthorizationResponse() *OAuth2ApiDeviceAuthorizationResponse {
	this := OAuth2ApiDeviceAuthorizationResponse{}
	return &this
}

// NewOAuth2ApiDeviceAuthorizationResponseWithDefaults instantiates a new OAuth2ApiDeviceAuthorizationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuth2ApiDeviceAuthorizationResponseWithDefaults() *OAuth2ApiDeviceAuthorizationResponse {
	this := OAuth2ApiDeviceAuthorizationResponse{}
	return &this
}

// GetDeviceCode returns the DeviceCode field value if set, zero value otherwise.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetDeviceCode() string {
	if o == nil || o.DeviceCode == nil {
		var ret string
		return ret
	}
	return *o.DeviceCode
}

// GetDeviceCodeOk returns a tuple with the DeviceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetDeviceCodeOk() (*string, bool) {
	if o == nil || o.DeviceCode == nil {
		return nil, false
	}
	return o.DeviceCode, true
}

// HasDeviceCode returns a boolean if a field has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) HasDeviceCode() bool {
	if o != nil && o.DeviceCode != nil {
		return true
	}

	return false
}

// SetDeviceCode gets a reference to the given string and assigns it to the DeviceCode field.
func (o *OAuth2ApiDeviceAuthorizationResponse) SetDeviceCode(v string) {
	o.DeviceCode = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetExpiresIn() int64 {
	if o == nil || o.ExpiresIn == nil {
		var ret int64
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetExpiresInOk() (*int64, bool) {
	if o == nil || o.ExpiresIn == nil {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) HasExpiresIn() bool {
	if o != nil && o.ExpiresIn != nil {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int64 and assigns it to the ExpiresIn field.
func (o *OAuth2ApiDeviceAuthorizationResponse) SetExpiresIn(v int64) {
	o.ExpiresIn = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetInterval() int64 {
	if o == nil || o.Interval == nil {
		var ret int64
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetIntervalOk() (*int64, bool) {
	if o == nil || o.Interval == nil {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) HasInterval() bool {
	if o != nil && o.Interval != nil {
		return true
	}

	return false
}

// SetInterval gets a reference to the given int64 and assigns it to the Interval field.
func (o *OAuth2ApiDeviceAuthorizationResponse) SetInterval(v int64) {
	o.Interval = &v
}

// GetUserCode returns the UserCode field value if set, zero value otherwise.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetUserCode() string {
	if o == nil || o.UserCode == nil {
		var ret string
		return ret
	}
	return *o.UserCode
}

// GetUserCodeOk returns a tuple with the UserCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetUserCodeOk() (*string, bool) {
	if o == nil || o.UserCode == nil {
		return nil, false
	}
	return o.UserCode, true
}

// HasUserCode returns a boolean if a field has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) HasUserCode() bool {
	if o != nil && o.UserCode != nil {
		return true
	}

	return false
}

// SetUserCode gets a reference to the given string and assigns it to the UserCode field.
func (o *OAuth2ApiDeviceAuthorizationResponse) SetUserCode(v string) {
	o.UserCode = &v
}

// GetVerificationUri returns the VerificationUri field value if set, zero value otherwise.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetVerificationUri() string {
	if o == nil || o.VerificationUri == nil {
		var ret string
		return ret
	}
	return *o.VerificationUri
}

// GetVerificationUriOk returns a tuple with the VerificationUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetVerificationUriOk() (*string, bool) {
	if o == nil || o.VerificationUri == nil {
		return nil, false
	}
	return o.VerificationUri, true
}

// HasVerificationUri returns a boolean if a field has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) HasVerificationUri() bool {
	if o != nil && o.VerificationUri != nil {
		return true
	}

	return false
}

// SetVerificationUri gets a reference to the given string and assigns it to the VerificationUri field.
func (o *OAuth2ApiDeviceAuthorizationResponse) SetVerificationUri(v string) {
	o.VerificationUri = &v
}

// GetVerificationUriComplete returns the VerificationUriComplete field value if set, zero value otherwise.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetVerificationUriComplete() string {
	if o == nil || o.VerificationUriComplete == nil {
		var ret string
		return ret
	}
	return *o.VerificationUriComplete
}

// GetVerificationUriCompleteOk returns a tuple with the VerificationUriComplete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) GetVerificationUriCompleteOk() (*string, bool) {
	if o == nil || o.VerificationUriComplete == nil {
		return nil, false
	}
	return o.VerificationUriComplete, true
}

// HasVerificationUriComplete returns a boolean if a field has been set.
func (o *OAuth2ApiDeviceAuthorizationResponse) HasVerificationUriComplete() bool {
	if o != nil && o.VerificationUriComplete != nil {
		return true
	}

	return false
}

// SetVerificationUriComplete gets a reference to the given string and assigns it to the VerificationUriComplete field.
func (o *OAuth2ApiDeviceAuthorizationResponse) SetVerificationUriComplete(v string) {
	o.VerificationUriComplete = &v
}

func (o OAuth2ApiDeviceAuthorizationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeviceCode != nil {
		toSerialize["device_code"] = o.DeviceCode
	}
	if o.ExpiresIn != nil {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if o.Interval != nil {
		toSerialize["interval"] = o.Interval
	}
	if o.UserCode != nil {
		toSerialize["user_code"] = o.UserCode
	}
	if o.VerificationUri != nil {
		toSerialize["verification_uri"] = o.VerificationUri
	}
	if o.VerificationUriComplete != nil {
		toSerialize["verification_uri_complete"] = o.VerificationUriComplete
	}
	return json.Marshal(toSerialize)
}

type NullableOAuth2ApiDeviceAuthorizationResponse struct {
	value *OAuth2ApiDeviceAuthorizationResponse
	isSet bool
}

func (v NullableOAuth2ApiDeviceAuthorizationResponse) Get() *OAuth2ApiDeviceAuthorizationResponse {
	return v.value
}

func (v *NullableOAuth2ApiDeviceAuthorizationResponse) Set(val *OAuth2ApiDeviceAuthorizationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2ApiDeviceAuthorizationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2ApiDeviceAuthorizationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2ApiDeviceAuthorizationResponse(val *OAuth2ApiDeviceAuthorizationResponse) *NullableOAuth2ApiDeviceAuthorizationResponse {
	return &NullableOAuth2ApiDeviceAuthorizationResponse{value: val, isSet: true}
}

func (v NullableOAuth2ApiDeviceAuthorizationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2ApiDeviceAuthorizationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
