// Code generated by go-swagger; DO NOT EDIT.

package v0alpha2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPerformOAuth2DeviceFlowParams creates a new PerformOAuth2DeviceFlowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPerformOAuth2DeviceFlowParams() *PerformOAuth2DeviceFlowParams {
	return &PerformOAuth2DeviceFlowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPerformOAuth2DeviceFlowParamsWithTimeout creates a new PerformOAuth2DeviceFlowParams object
// with the ability to set a timeout on a request.
func NewPerformOAuth2DeviceFlowParamsWithTimeout(timeout time.Duration) *PerformOAuth2DeviceFlowParams {
	return &PerformOAuth2DeviceFlowParams{
		timeout: timeout,
	}
}

// NewPerformOAuth2DeviceFlowParamsWithContext creates a new PerformOAuth2DeviceFlowParams object
// with the ability to set a context for a request.
func NewPerformOAuth2DeviceFlowParamsWithContext(ctx context.Context) *PerformOAuth2DeviceFlowParams {
	return &PerformOAuth2DeviceFlowParams{
		Context: ctx,
	}
}

// NewPerformOAuth2DeviceFlowParamsWithHTTPClient creates a new PerformOAuth2DeviceFlowParams object
// with the ability to set a custom HTTPClient for a request.
func NewPerformOAuth2DeviceFlowParamsWithHTTPClient(client *http.Client) *PerformOAuth2DeviceFlowParams {
	return &PerformOAuth2DeviceFlowParams{
		HTTPClient: client,
	}
}

/* PerformOAuth2DeviceFlowParams contains all the parameters to send to the API endpoint
   for the perform o auth2 device flow operation.

   Typically these are written to a http.Request.
*/
type PerformOAuth2DeviceFlowParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the perform o auth2 device flow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PerformOAuth2DeviceFlowParams) WithDefaults() *PerformOAuth2DeviceFlowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the perform o auth2 device flow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PerformOAuth2DeviceFlowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the perform o auth2 device flow params
func (o *PerformOAuth2DeviceFlowParams) WithTimeout(timeout time.Duration) *PerformOAuth2DeviceFlowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the perform o auth2 device flow params
func (o *PerformOAuth2DeviceFlowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the perform o auth2 device flow params
func (o *PerformOAuth2DeviceFlowParams) WithContext(ctx context.Context) *PerformOAuth2DeviceFlowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the perform o auth2 device flow params
func (o *PerformOAuth2DeviceFlowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the perform o auth2 device flow params
func (o *PerformOAuth2DeviceFlowParams) WithHTTPClient(client *http.Client) *PerformOAuth2DeviceFlowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the perform o auth2 device flow params
func (o *PerformOAuth2DeviceFlowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PerformOAuth2DeviceFlowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
