// Code generated by go-swagger; DO NOT EDIT.

package v0alpha2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new v0alpha2 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for v0alpha2 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PerformOAuth2DeviceFlow(params *PerformOAuth2DeviceFlowParams, opts ...ClientOption) (*PerformOAuth2DeviceFlowOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PerformOAuth2DeviceFlow thes o auth 2 0 device authorize endpoint

  This endpoint is not documented here because you should never use your own implementation to perform OAuth2 flows.
OAuth2 is a very popular protocol and a library for your programming language will exists.

To learn more about this flow please refer to the specification: https://tools.ietf.org/html/rfc8628
*/
func (a *Client) PerformOAuth2DeviceFlow(params *PerformOAuth2DeviceFlowParams, opts ...ClientOption) (*PerformOAuth2DeviceFlowOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPerformOAuth2DeviceFlowParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "performOAuth2DeviceFlow",
		Method:             "GET",
		PathPattern:        "/oauth2/device/auth",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PerformOAuth2DeviceFlowReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PerformOAuth2DeviceFlowOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for performOAuth2DeviceFlow: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
